/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_powsybl_pgm_PgmWrapper */

#ifndef _Included_com_powsybl_pgm_PgmWrapper
#define _Included_com_powsybl_pgm_PgmWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    createCppObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_powsybl_pgm_PgmWrapper_createCppObject
  (JNIEnv *, jobject);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    workOnCppObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_workOnCppObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    deleteCppObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_deleteCppObject
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    addNode
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_addNode
  (JNIEnv *, jobject, jlong, jint, jdouble);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    addSource
 * Signature: (JIIZD)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_addSource
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jdouble);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    addSymLoaGendInput
 * Signature: (JIIZIDD)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_addSymLoaGendInput
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jint, jdouble, jdouble);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    addLine
 * Signature: (JIIZIZDDDDD)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_addLine
  (JNIEnv *, jobject, jlong, jint, jint, jboolean, jint, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    finalizeConstruction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_finalizeConstruction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_powsybl_pgm_PgmWrapper
 * Method:    runPf
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_powsybl_pgm_PgmWrapper_runPf
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
